name: celeb-matcher
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3002:80
    depends_on:
      - backend
      - frontend
    networks:
      - my_network

  frontend:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - my_network

  backend:
    image: celeb-matcher/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: "node src/server.js"
    env_file: "./.env"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
